/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using System.Runtime.Serialization;

public class Constants
{
  /// <summary>
  /// Thrift also lets you define constants for use across languages. Complex
  /// types and structs are specified using JSON notation.
  /// </summary>
  public static int INT32CONSTANT = 9853;
  public static Dictionary<string, string> MAPCONSTANT = new Dictionary<string, string>();
  static Constants()
  {
    MAPCONSTANT["hello"] = "world";
    MAPCONSTANT["goodnight"] = "moon";
  }
}
