//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by notepadre.rc
//
#define IDD_PAGE_SETUP                  12
#define IDC_EDIT_HEADER                 30
#define IDC_EDIT_FOOTER                 31
#define IDD_ABOUTBOX                    100
#define IDR_MAINFRAME                   128
#define IDR_NOTERETYPE                  129
#define IDR_DOCUMENT                    129
#define IDD_GOTO                        130
#define IDD_FIND                        134
#define IDD_FIND_REPLACE                135
#define IDD_ENCODING_FILE_DLG           136
#define IDD_REGEX_SYNTAX                140
#define IDC_EDIT_LINE                   1000
#define IDC_EDIT_COLUMN                 1001
#define IDC_EDIT_FIND                   1002
#define IDC_CHECK_WHOLE_WORD            1003
#define IDC_CHECK_MATCH_CASE            1004
#define IDC_CHECK_REGEX                 1005
#define IDC_RADIO_UP                    1006
#define IDC_RADIO_DOWN                  1007
#define IDC_BUTTON_HELP                 1008
#define IDC_EDIT_REPLACE                1009
#define IDC_BUTTON_REPLACE              1010
#define IDC_BUTTON_REPLACE_ALL          1011
#define IDC_CHECK_CLOSE_ON_MATCH        1012
#define IDC_COMBO_ENCODING              1013
#define IDC_CHECK_LIKE_NOTEPAD          1015
#define IDC_BUTTON_URL                  1016
#define IDC_RADIO_PERL_SUBSET           1017
#define IDC_RADIO_BASIC_POSIX           1018
#define IDC_RADIO_EXTENDED_POSIX        1019
#define IDC_RADIO_EMACS                 1020
#define IDC_RADIO_AWK                   1021
#define IDC_RADIO_GREP                  1022
#define IDC_RADIO_EGREP                 1023
#define IDC_CHECK_ESCAPE_IN_LISTS       1024
#define IDC_CHECK_CHAR_CLASSES          1025
#define IDC_CHECK_INTERVALS             1026
#define IDC_CHECK_LIMITED_OPS           1027
#define IDC_CHECK_NEWLINE_ALT           1028
#define IDC_CHECK_BK_PLUS_QM            1029
#define IDC_RADIO_NONE                  1030
#define IDC_CHECK_BK_BRACES             1031
#define IDC_CHECK_BK_PARENS             1032
#define IDC_CHECK_BK_REFS               1033
#define IDC_CHECK_BK_VBAR               1034
#define IDC_CHECK_COLLATE               1035
#define IDC_CHECK_PERLEX                1036
#define IDC_CHECK_NOSUBS                1037
#define IDC_CHECK_NOT_NULL              1038
#define IDC_CHECK_CONTINUOUS            1039
#define IDC_CHECK_SINGLE_LINE           1040
#define IDC_CHECK_NOT_DOT_NEWLINE       1041
#define IDC_CHECK_NOT_DOT_NULL          1042
#define IDC_CHECK_SED                   1043
#define IDC_CHECK_ALL                   1044
#define IDC_CHECK_FIRST_ONLY            1045
#define IDC_CHECK_LITERAL               1046
#define IDC_CHECK_ANY                   1047
#define IDC_CHECK_EXTRA                 1048
#define IDC_CHECK_PERL                  1049
#define IDC_COMBO_FORMAT                1053
#define ID_EDIT_GOTO                    32771
#define ID_EDIT_TIMEDATE                32772
#define ID_FORMAT_WORD_WRAP             32773
#define ID_OPTIONS_DROP_FILES           32774
#define ID_OPTIONS_FILE_CHANGE_NOTIFY   32775
#define ID_HELP_REGEX                   32776
#define ID_OPTIONS_SCROLL_TO_END        32777
#define ID_OPTIONS_AUTO_LOAD            32778
#define ID_OPTIONS_AUTO_RELOAD          32779
#define ID_OPTIONS_REGEX_SYNTAX         32780
#define ID_FORMAT_READ_ONLY             32781
#define IDS_ENCODING_HELP               62011
#define IDS_UNIX_FORMAT_HELP            62012
#define IDS_FORMAT_HELP                 62012
#define IDS_FIND_WHAT                   62013
#define IDS_REPLACE_WHAT                62014
#define IDS_WHOLE_WORD_ONLY             62015
#define IDS_MATCH_CASE                  62016
#define IDS_REGULAR_EXPRESSION          62017
#define IDS_UP                          62018
#define IDS_DOWN                        62019
#define IDS_CLOSE_ON_MATCH              62020
#define IDS_FIND_NEXT                   62021
#define IDS_REPLACE                     62022
#define IDS_REPLACE_ALL                 62023
#define IDS_CANCEL                      62024
#define IDS_HELP                        62025
#define IDS_LINE                        62026
#define IDS_COLUMN                      62027
#define IDS_OK_GOTO                     62028
#define IDS_ANSI                        62029
#define IDS_UNICODE                     62030
#define IDS_UNICODE_BIG_ENDIAN          62031
#define IDS_UTF_8                       62032
#define IDS_ARIAL_8                     62033
#define IDS_LN_COL_FMT                  62034
#define IDS_NOTEPAD_REG_KEY             62035
#define IDS_NOTEPADRE_REG_KEY           62036
#define IDS_DROP_FILES                  62037
#define IDS_FAILED_TO_CREATE_TOOLBAR    62038
#define IDS_FAILED_TO_CREATE_STATUS_BAR 62039
#define IDS_LN_COL_MAX                  62040
#define IDS_WINDOW_POS_DX               62041
#define IDS_WINDOW_POS_DY               62042
#define IDS_WINDOW_POS_X                62043
#define IDS_WINDOW_POS_Y                62044
#define IDS_NOTEPAD_CHM                 62045
#define IDS_RELEASE_NOTEPADRE_CHM       62046
#define IDS_DOT_HLP                     62047
#define IDS_DOT_CHM                     62048
#define IDS_CR_LF                       62049
#define IDS_STAR_DOT_STAR               62050
#define IDS_BEN_HANSON                  62051
#define IDS_REG_EX                      62052
#define IDS_FILE_CHANGE_NOTIFY          62053
#define IDS_CREATE_THREAD_FAILED        62054
#define IDS_FIND_FIRST_CHANGE_NOTIFICATION_FAILED 62055
#define IDS_FIND_CLOSE_CHANGE_NOTIFICATION_FAILED 62056
#define IDS_CANNOT_FIND_FMT             62057
#define IDS_DOT_LOG                     62058
#define IDS_VALID_CHARS                 62059
#define IDS_NO_WRITE_TIME_CHANGE        62060
#define IDS_EDIT                        62061
#define IDS_WRAP                        62062
#define IDS_NOTEPAD_RE                  62065
#define IDS_POINT_SIZE                  62066
#define IDS_ESCAPEMENT                  62067
#define IDS_ORIENTATION                 62068
#define IDS_WEIGHT                      62069
#define IDS_ITALIC                      62070
#define IDS_UNDERLINE                   62071
#define IDS_STRIKE_OUT                  62072
#define IDS_CHAR_SET                    62073
#define IDS_OUT_PRECISION               62074
#define IDS_CLIP_PRECISION              62075
#define IDS_QUALITY                     62076
#define IDS_PITCH_AND_FAMILY            62077
#define IDS_FACE_NAME                   62078
#define IDS_MODIFIED_OUTSIDE_FMT        62079
#define IDS_VIEW_TOOL_BAR               62080
#define IDS_VIEW_STATUS_BAR             62081
#define IDS_LIKE_NOTEPAD                62082
#define IDS_SCROLL_TO_END               62083
#define IDS_AUTO_RELOAD                 62084
#define IDS_MARGIN_BOTTOM               62085
#define IDS_MARGIN_LEFT                 62086
#define IDS_MARGIN_RIGHT                62087
#define IDS_MARGIN_TOP                  62088
#define IDS_HEADER                      62089
#define IDS_TRAILER                     62090
#define IDS_WINDOWS                     62091
#define IDS_UNIX                        62092
#define IDS_MACINTOSH                   62093
#define IDS_ESCAPE_IN_LISTS             62094
#define IDS_CHAR_CLASSES                62095
#define IDS_INTERVALS                   62096
#define IDS_LIMITED_OPS                 62097
#define IDS_NEWLINE_ALT                 62098
#define IDS_BK_PLUS_QM                  62099
#define IDS_BK_BRACES                   62100
#define IDS_BK_PARENS                   62101
#define IDS_BK_REFS                     62102
#define IDS_BK_VBAR                     62103
#define IDS_LITERAL                     62104
#define IDS_COLLATE                     62105
#define IDS_PERLEX                      62106
#define IDS_NOSUBS                      62107
#define IDS_MATCH_NOT_DOT_NEWLINE       62108
#define IDS_MATCH_NOT_DOT_NULL          62109
#define IDS_MATCH_ANY                   62110
#define IDS_MATCH_NOT_NULL              62111
#define IDS_MATCH_CONTINUOUS            62112
#define IDS_MATCH_EXTRA                 62113
#define IDS_MATCH_SINGLE_LINE           62114
#define IDS_FORMAT_PERL                 62115
#define IDS_FORMAT_SED                  62116
#define IDS_FORMAT_ALL                  62117
#define IDS_FORMAT_FIRST_ONLY           62118
#define IDS_FIND_DOCKED                 62119
#define IDS_REPLACE_DOCKED              62120
#define IDS_FIND_DOCK_ID                62121
#define IDS_REPLACE_DOCK_ID             62122

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        142
#define _APS_NEXT_COMMAND_VALUE         32782
#define _APS_NEXT_CONTROL_VALUE         1056
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
