USE MYSQL;
DELETE FROM user WHERE user='DG_Admin';

DROP DATABASE IF EXISTS DG_Game;
CREATE DATABASE DG_Game;
GRANT ALL PRIVILEGES ON DG_Game.* TO DG_Admin@'%' IDENTIFIED BY '1111';
use DG_Game;


DROP DATABASE IF EXISTS DG_Log;
CREATE DATABASE DG_Log;
GRANT ALL PRIVILEGES ON DG_Log.* TO DG_Admin@'%' IDENTIFIED BY '1111';
use DG_Log;
