/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef BingoGameServer_CONSTANTS_H
#define BingoGameServer_CONSTANTS_H

#include "BingoGameServer_types.h"

namespace nBingo {

class BingoGameServerConstants {
 public:
  BingoGameServerConstants();

};

extern const BingoGameServerConstants g_BingoGameServer_constants;

} // namespace

#endif
