
// this code is generated by PacketGenerator(lib_mech)
// 주의 http://www.frictionpointstudios.com/blog/2011/3/31/using-protobuf-net-serialization-in-unity-iphone.html 를 사용할때 쓰는 코드 

using System; //from ProtocalPrototype.xml : GOOGLE_PROTOCAL_BUFFER : include_namespace
using System.Collections; //from ProtocalPrototype.xml : GOOGLE_PROTOCAL_BUFFER : include_namespace
using System.Collections.Generic; //from ProtocalPrototype.xml : GOOGLE_PROTOCAL_BUFFER : include_namespace
using System.Text; //from ProtocalPrototype.xml : GOOGLE_PROTOCAL_BUFFER : include_namespace
using ProtoBuf; //from ProtocalPrototype.xml : GOOGLE_PROTOCAL_BUFFER : include_namespace
using nEXCEL; //from ProtocalPrototype.xml : GOOGLE_PROTOCAL_BUFFER : include_namespace
using nPROTO; //from ProtocalPrototype.xml : GOOGLE_PROTOCAL_BUFFER : include_namespace
namespace nPROTO
{
	// group : BaseballServer_UserGateServer

	[ProtoContract]
	public class s_bs2ug_set_cvar
	{
		[ProtoMember(1, IsRequired = false)]
		public string name {get; set;} 
		[ProtoMember(2, IsRequired = false)]
		public string val {get; set;} 
	} //public class s__bs2ug_set_cvar


	[ProtoContract]
	public class s_bs2ug_game_end
	{
		[ProtoMember(1, IsRequired = false)]
		public s_result_game rg {get; set;} 
		[ProtoMember(2, IsRequired = false)]
		public bool is_better {get; set;} 
		[ProtoMember(3, IsRequired = false)]
		public List<s_result_round> rr {get; set;} 
		
		public s_bs2ug_game_end()
		{
			rr = new List<s_result_round>();
		}
	} //public class s__bs2ug_game_end


	[ProtoContract]
	public class s_bs2ug_echo
	{
		[ProtoMember(1, IsRequired = false)]
		public Int32 type {get; set;} 
		[ProtoMember(2, IsRequired = false)]
		public string msg {get; set;} 
		[ProtoMember(3, IsRequired = false)]
		public Int64 bs_time_msec {get; set;} 
		[ProtoMember(4, IsRequired = false)]
		public Int64 ug_time_msec {get; set;} 
	} //public class s__bs2ug_echo


	[ProtoContract]
	public class s_bs2ug_error
	{
		[ProtoMember(1, IsRequired = false)]
		public Int32 sys_error_id {get; set;} 
	} //public class s__bs2ug_error


	[ProtoContract]
	public class s_bs2ug_add_discon_tot
	{
		[ProtoMember(1, IsRequired = false)]
		public Int64 discon_uid {get; set;} 
	} //public class s__bs2ug_add_discon_tot



	// group : BaseballServer_Client

	[ProtoContract]
	public class s_ans_join_room
	{
		[ProtoMember(1, IsRequired = false)]
		public GameRoomInfo gri {get; set;} 
	} //public class s__ans_join_room


	[ProtoContract]
	public class s_ans_room_state
	{
		[ProtoMember(1, IsRequired = false)]
		public GameRoomInfo gri {get; set;} 
	} //public class s__ans_room_state


	[ProtoContract]
	public class s_bs2x_echo
	{
		[ProtoMember(1, IsRequired = false)]
		public Int32 type {get; set;} 
		[ProtoMember(2, IsRequired = false)]
		public string msg {get; set;} 
		[ProtoMember(3, IsRequired = false)]
		public Int32 client_time_msec {get; set;} 
		[ProtoMember(4, IsRequired = false)]
		public Int64 bs_time_msec {get; set;} 
	} //public class s__bs2x_echo


	[ProtoContract]
	public class s_ans_chat
	{
		[ProtoMember(1, IsRequired = false)]
		public Int32 type {get; set;} 
		[ProtoMember(2, IsRequired = false)]
		public string msg {get; set;} 
		[ProtoMember(3, IsRequired = false)]
		public string etc {get; set;} 
	} //public class s__ans_chat


	[ProtoContract]
	public class s_ans_timer_start
	{
		[ProtoMember(1, IsRequired = false)]
		public Int32 count {get; set;} 
		[ProtoMember(2, IsRequired = false)]
		public string msg {get; set;} 
	} //public class s__ans_timer_start


	[ProtoContract]
	public class s_bs2x_echo2
	{
		[ProtoMember(1, IsRequired = false)]
		public Int32 type {get; set;} 
		[ProtoMember(2, IsRequired = false)]
		public string msg {get; set;} 
		[ProtoMember(3, IsRequired = false)]
		public Int32 client_time_msec {get; set;} 
		[ProtoMember(4, IsRequired = false)]
		public Int64 bs_time_msec {get; set;} 
		[ProtoMember(5, IsRequired = false)]
		public Int32 etc {get; set;} 
	} //public class s__bs2x_echo2


	[ProtoContract]
	public class s_ans_bs_error
	{
		[ProtoMember(1, IsRequired = false)]
		public Int32 sys_error_id {get; set;} 
	} //public class s__ans_bs_error


	[ProtoContract]
	public class s_bs2x_auto_match_ready2
	{
		[ProtoMember(1, IsRequired = false)]
		public Int64 uid {get; set;} 
		[ProtoMember(2, IsRequired = false)]
		public Int32 batter {get; set;} 
		[ProtoMember(3, IsRequired = false)]
		public Int32 pitcher {get; set;} 
		[ProtoMember(4, IsRequired = false)]
		public Int32 other_batter {get; set;} 
		[ProtoMember(5, IsRequired = false)]
		public Int32 other_pitcher {get; set;} 
	} //public class s__bs2x_auto_match_ready2


	[ProtoContract]
	public class s_ans_game_start
	{
		[ProtoMember(1, IsRequired = false)]
		public Int64 attack_user {get; set;} 
		[ProtoMember(2, IsRequired = false)]
		public Int32 sid_Sys_Runner_State {get; set;} 
		[ProtoMember(3, IsRequired = false)]
		public Int32 baseball_park {get; set;} 
	} //public class s__ans_game_start


	[ProtoContract]
	public class s_ans_game_round_start
	{
		[ProtoMember(1, IsRequired = false)]
		public Int32 round {get; set;} 
		[ProtoMember(2, IsRequired = false)]
		public Int32 runner_state {get; set;} 
	} //public class s__ans_game_round_start


	[ProtoContract]
	public class s_bs2x_match_ready
	{
		[ProtoMember(1, IsRequired = false)]
		public Int64 uid {get; set;} 
	} //public class s__bs2x_match_ready


	[ProtoContract]
	public class s_ans_pitcher_throw
	{
		[ProtoMember(1, IsRequired = false)]
		public s_pitcher_throw_info info {get; set;} 
		[ProtoMember(2, IsRequired = false)]
		public bool is_auto {get; set;} 
	} //public class s__ans_pitcher_throw


	[ProtoContract]
	public class s_ans_better_hit
	{
		[ProtoMember(1, IsRequired = false)]
		public s_better_hit_info info {get; set;} 
		[ProtoMember(2, IsRequired = false)]
		public bool is_auto {get; set;} 
	} //public class s__ans_better_hit


	[ProtoContract]
	public class s_ans_result_better_hit
	{
		[ProtoMember(1, IsRequired = false)]
		public s_result_round info {get; set;} 
		[ProtoMember(2, IsRequired = false)]
		public Int32 end_type {get; set;} 
	} //public class s__ans_result_better_hit


	[ProtoContract]
	public class s_bs2x_batter_ready
	{
	} //public class s__bs2x_batter_ready


	[ProtoContract]
	public class s_ans_change_attack_team
	{
		[ProtoMember(1, IsRequired = false)]
		public Int32 round {get; set;} 
		[ProtoMember(2, IsRequired = false)]
		public Int64 attack_user {get; set;} 
	} //public class s__ans_change_attack_team


	[ProtoContract]
	public class s_ans_game_end
	{
		[ProtoMember(1, IsRequired = false)]
		public s_result_game rg {get; set;} 
		[ProtoMember(2, IsRequired = false)]
		public s_tbl_user user {get; set;} 
		[ProtoMember(3, IsRequired = false)]
		public Int32 end_type {get; set;} 
	} //public class s__ans_game_end


	[ProtoContract]
	public class s_bs2x_game_end_other_user_info
	{
		[ProtoMember(1, IsRequired = false)]
		public s_tbl_user other_user {get; set;} 
	} //public class s__bs2x_game_end_other_user_info


	[ProtoContract]
	public class s_ans_user_disconnect
	{
		[ProtoMember(1, IsRequired = false)]
		public Int64 uid {get; set;} 
		[ProtoMember(2, IsRequired = false)]
		public Int32 sys_error_id {get; set;} 
	} //public class s__ans_user_disconnect


	[ProtoContract]
	public class s_ans_rematch
	{
		[ProtoMember(1, IsRequired = false)]
		public Int64 uid {get; set;} 
	} //public class s__ans_rematch


	[ProtoContract]
	public class s_ans_answer_restart_game
	{
		[ProtoMember(1, IsRequired = false)]
		public List<Int64> uid {get; set;} 
		[ProtoMember(2, IsRequired = false)]
		public List<bool> ok {get; set;} 
		[ProtoMember(3, IsRequired = false)]
		public Int32 baseball_park {get; set;} 
		[ProtoMember(4, IsRequired = false)]
		public Int64 attack_user {get; set;} 
		
		public s_ans_answer_restart_game()
		{
			ok = new List<bool>();
			uid = new List<Int64>();
		}
	} //public class s__ans_answer_restart_game



	// group : UserGateServer_BaseballServer

	[ProtoContract]
	public class s_ug2bs_ans_set_cvar
	{
		[ProtoMember(1, IsRequired = false)]
		public string name {get; set;} 
		[ProtoMember(2, IsRequired = false)]
		public string val {get; set;} 
	} //public class s__ug2bs_ans_set_cvar


	[ProtoContract]
	public class s_ug2bs_game_end
	{
		[ProtoMember(1, IsRequired = false)]
		public s_result_game rg {get; set;} 
		[ProtoMember(2, IsRequired = false)]
		public s_tbl_user user {get; set;} 
	} //public class s__ug2bs_game_end


	[ProtoContract]
	public class s_ug2bs_echo
	{
		[ProtoMember(1, IsRequired = false)]
		public Int32 type {get; set;} 
		[ProtoMember(2, IsRequired = false)]
		public string msg {get; set;} 
		[ProtoMember(3, IsRequired = false)]
		public Int64 bs_time_msec {get; set;} 
		[ProtoMember(4, IsRequired = false)]
		public Int64 ug_time_msec {get; set;} 
	} //public class s__ug2bs_echo


	[ProtoContract]
	public class s_ug2bs_error
	{
		[ProtoMember(1, IsRequired = false)]
		public Int32 sys_error_id {get; set;} 
	} //public class s__ug2bs_error


	[ProtoContract]
	public class s_ug2bs_add_discon_tot
	{
		[ProtoMember(1, IsRequired = false)]
		public Int64 discon_uid {get; set;} 
	} //public class s__ug2bs_add_discon_tot



	// group : Client_BaseballServer

	[ProtoContract]
	public class s_req_room_state
	{
		[ProtoMember(1, IsRequired = false)]
		public Int32 room {get; set;} 
	} //public class s__req_room_state


	[ProtoContract]
	public class s_x2bs_echo
	{
		[ProtoMember(1, IsRequired = false)]
		public Int32 type {get; set;} 
		[ProtoMember(2, IsRequired = false)]
		public string msg {get; set;} 
		[ProtoMember(3, IsRequired = false)]
		public Int32 client_time_msec {get; set;} 
	} //public class s__x2bs_echo


	[ProtoContract]
	public class s_req_chat
	{
		[ProtoMember(1, IsRequired = false)]
		public Int32 type {get; set;} 
		[ProtoMember(2, IsRequired = false)]
		public string msg {get; set;} 
		[ProtoMember(3, IsRequired = false)]
		public string etc {get; set;} 
	} //public class s__req_chat


	[ProtoContract]
	public class s_req_timer_start
	{
		[ProtoMember(1, IsRequired = false)]
		public Int32 term {get; set;} 
		[ProtoMember(2, IsRequired = false)]
		public string msg {get; set;} 
	} //public class s__req_timer_start


	[ProtoContract]
	public class s_req_do_disconnect
	{
		[ProtoMember(1, IsRequired = false)]
		public string reason {get; set;} 
	} //public class s__req_do_disconnect


	[ProtoContract]
	public class s_x2bs_echo2
	{
		[ProtoMember(1, IsRequired = false)]
		public Int32 type {get; set;} 
		[ProtoMember(2, IsRequired = false)]
		public string msg {get; set;} 
		[ProtoMember(3, IsRequired = false)]
		public Int32 client_time_msec {get; set;} 
	} //public class s__x2bs_echo2


	[ProtoContract]
	public class s_req_get_cvar
	{
		[ProtoMember(1, IsRequired = false)]
		public string name {get; set;} 
	} //public class s__req_get_cvar


	[ProtoContract]
	public class s_req_set_cvar
	{
		[ProtoMember(1, IsRequired = false)]
		public string name {get; set;} 
		[ProtoMember(2, IsRequired = false)]
		public string val {get; set;} 
	} //public class s__req_set_cvar


	[ProtoContract]
	public class s_x2bs_auto_match_ready2
	{
		[ProtoMember(1, IsRequired = false)]
		public Int64 uid {get; set;} 
		[ProtoMember(2, IsRequired = false)]
		public Int32 batter {get; set;} 
		[ProtoMember(3, IsRequired = false)]
		public Int32 pitcher {get; set;} 
	} //public class s__x2bs_auto_match_ready2


	[ProtoContract]
	public class s_x2bs_match_ready
	{
		[ProtoMember(1, IsRequired = false)]
		public Int64 uid {get; set;} 
	} //public class s__x2bs_match_ready


	[ProtoContract]
	public class s_req_pitcher_throw
	{
		[ProtoMember(1, IsRequired = false)]
		public s_pitcher_throw_info info {get; set;} 
		[ProtoMember(2, IsRequired = false)]
		public Int32 used_gesturetype {get; set;} 
		[ProtoMember(3, IsRequired = false)]
		public Int32 gesturetype_input_error {get; set;} 
	} //public class s__req_pitcher_throw


	[ProtoContract]
	public class s_req_better_hit
	{
		[ProtoMember(1, IsRequired = false)]
		public s_better_hit_info info {get; set;} 
	} //public class s__req_better_hit


	[ProtoContract]
	public class s_req_result_better_hit
	{
		[ProtoMember(1, IsRequired = false)]
		public s_result_round info {get; set;} 
		[ProtoMember(2, IsRequired = false)]
		public Int32 test {get; set;} 
	} //public class s__req_result_better_hit


	[ProtoContract]
	public class s_x2bs_batter_ready
	{
	} //public class s__x2bs_batter_ready


	[ProtoContract]
	public class s_req_rematch
	{
		[ProtoMember(1, IsRequired = false)]
		public Int64 uid {get; set;} 
	} //public class s__req_rematch


	[ProtoContract]
	public class s_req_answer_restart_game
	{
		[ProtoMember(1, IsRequired = false)]
		public Int64 uid {get; set;} 
		[ProtoMember(2, IsRequired = false)]
		public bool ok {get; set;} 
	} //public class s__req_answer_restart_game



	[ProtoContract]
	public class BaseballServer_UserGateServer {
		public enum Type {
			NONE = 1,

			bs2ug_set_cvar = 2,
			bs2ug_game_end = 3,
			bs2ug_echo = 4,
			bs2ug_error = 5,
			bs2ug_add_discon_tot = 6,
		}

		[ProtoMember(1,IsRequired = true)]
		public Type type {get; set;}

		[ProtoMember(2, IsRequired = false)]
		public s_bs2ug_set_cvar m_bs2ug_set_cvar {get; set;}
		[ProtoMember(3, IsRequired = false)]
		public s_bs2ug_game_end m_bs2ug_game_end {get; set;}
		[ProtoMember(4, IsRequired = false)]
		public s_bs2ug_echo m_bs2ug_echo {get; set;}
		[ProtoMember(5, IsRequired = false)]
		public s_bs2ug_error m_bs2ug_error {get; set;}
		[ProtoMember(6, IsRequired = false)]
		public s_bs2ug_add_discon_tot m_bs2ug_add_discon_tot {get; set;}
	}
//end of message BaseballServer_UserGateServer


	[ProtoContract]
	public class BaseballServer_Client {
		public enum Type {
			NONE = 1,

			ans_join_room = 2,
			ans_room_state = 3,
			bs2x_echo = 4,
			ans_chat = 5,
			ans_timer_start = 6,
			bs2x_echo2 = 7,
			ans_bs_error = 8,
			bs2x_auto_match_ready2 = 9,
			ans_game_start = 10,
			ans_game_round_start = 11,
			bs2x_match_ready = 12,
			ans_pitcher_throw = 13,
			ans_better_hit = 14,
			ans_result_better_hit = 15,
			bs2x_batter_ready = 16,
			ans_change_attack_team = 17,
			ans_game_end = 18,
			bs2x_game_end_other_user_info = 19,
			ans_user_disconnect = 20,
			ans_rematch = 21,
			ans_answer_restart_game = 22,
		}

		[ProtoMember(1,IsRequired = true)]
		public Type type {get; set;}

		[ProtoMember(2, IsRequired = false)]
		public s_ans_join_room m_ans_join_room {get; set;}
		[ProtoMember(3, IsRequired = false)]
		public s_ans_room_state m_ans_room_state {get; set;}
		[ProtoMember(4, IsRequired = false)]
		public s_bs2x_echo m_bs2x_echo {get; set;}
		[ProtoMember(5, IsRequired = false)]
		public s_ans_chat m_ans_chat {get; set;}
		[ProtoMember(6, IsRequired = false)]
		public s_ans_timer_start m_ans_timer_start {get; set;}
		[ProtoMember(7, IsRequired = false)]
		public s_bs2x_echo2 m_bs2x_echo2 {get; set;}
		[ProtoMember(8, IsRequired = false)]
		public s_ans_bs_error m_ans_bs_error {get; set;}
		[ProtoMember(9, IsRequired = false)]
		public s_bs2x_auto_match_ready2 m_bs2x_auto_match_ready2 {get; set;}
		[ProtoMember(10, IsRequired = false)]
		public s_ans_game_start m_ans_game_start {get; set;}
		[ProtoMember(11, IsRequired = false)]
		public s_ans_game_round_start m_ans_game_round_start {get; set;}
		[ProtoMember(12, IsRequired = false)]
		public s_bs2x_match_ready m_bs2x_match_ready {get; set;}
		[ProtoMember(13, IsRequired = false)]
		public s_ans_pitcher_throw m_ans_pitcher_throw {get; set;}
		[ProtoMember(14, IsRequired = false)]
		public s_ans_better_hit m_ans_better_hit {get; set;}
		[ProtoMember(15, IsRequired = false)]
		public s_ans_result_better_hit m_ans_result_better_hit {get; set;}
		[ProtoMember(16, IsRequired = false)]
		public s_bs2x_batter_ready m_bs2x_batter_ready {get; set;}
		[ProtoMember(17, IsRequired = false)]
		public s_ans_change_attack_team m_ans_change_attack_team {get; set;}
		[ProtoMember(18, IsRequired = false)]
		public s_ans_game_end m_ans_game_end {get; set;}
		[ProtoMember(19, IsRequired = false)]
		public s_bs2x_game_end_other_user_info m_bs2x_game_end_other_user_info {get; set;}
		[ProtoMember(20, IsRequired = false)]
		public s_ans_user_disconnect m_ans_user_disconnect {get; set;}
		[ProtoMember(21, IsRequired = false)]
		public s_ans_rematch m_ans_rematch {get; set;}
		[ProtoMember(22, IsRequired = false)]
		public s_ans_answer_restart_game m_ans_answer_restart_game {get; set;}
	}
//end of message BaseballServer_Client


	[ProtoContract]
	public class UserGateServer_BaseballServer {
		public enum Type {
			NONE = 1,

			ug2bs_ans_set_cvar = 2,
			ug2bs_game_end = 3,
			ug2bs_echo = 4,
			ug2bs_error = 5,
			ug2bs_add_discon_tot = 6,
		}

		[ProtoMember(1,IsRequired = true)]
		public Type type {get; set;}

		[ProtoMember(2, IsRequired = false)]
		public s_ug2bs_ans_set_cvar m_ug2bs_ans_set_cvar {get; set;}
		[ProtoMember(3, IsRequired = false)]
		public s_ug2bs_game_end m_ug2bs_game_end {get; set;}
		[ProtoMember(4, IsRequired = false)]
		public s_ug2bs_echo m_ug2bs_echo {get; set;}
		[ProtoMember(5, IsRequired = false)]
		public s_ug2bs_error m_ug2bs_error {get; set;}
		[ProtoMember(6, IsRequired = false)]
		public s_ug2bs_add_discon_tot m_ug2bs_add_discon_tot {get; set;}
	}
//end of message UserGateServer_BaseballServer


	[ProtoContract]
	public class Client_BaseballServer {
		public enum Type {
			NONE = 1,

			req_room_state = 2,
			x2bs_echo = 3,
			req_chat = 4,
			req_timer_start = 5,
			req_do_disconnect = 6,
			x2bs_echo2 = 7,
			req_get_cvar = 8,
			req_set_cvar = 9,
			x2bs_auto_match_ready2 = 10,
			x2bs_match_ready = 11,
			req_pitcher_throw = 12,
			req_better_hit = 13,
			req_result_better_hit = 14,
			x2bs_batter_ready = 15,
			req_rematch = 16,
			req_answer_restart_game = 17,
		}

		[ProtoMember(1,IsRequired = true)]
		public Type type {get; set;}

		[ProtoMember(2, IsRequired = false)]
		public s_req_room_state m_req_room_state {get; set;}
		[ProtoMember(3, IsRequired = false)]
		public s_x2bs_echo m_x2bs_echo {get; set;}
		[ProtoMember(4, IsRequired = false)]
		public s_req_chat m_req_chat {get; set;}
		[ProtoMember(5, IsRequired = false)]
		public s_req_timer_start m_req_timer_start {get; set;}
		[ProtoMember(6, IsRequired = false)]
		public s_req_do_disconnect m_req_do_disconnect {get; set;}
		[ProtoMember(7, IsRequired = false)]
		public s_x2bs_echo2 m_x2bs_echo2 {get; set;}
		[ProtoMember(8, IsRequired = false)]
		public s_req_get_cvar m_req_get_cvar {get; set;}
		[ProtoMember(9, IsRequired = false)]
		public s_req_set_cvar m_req_set_cvar {get; set;}
		[ProtoMember(10, IsRequired = false)]
		public s_x2bs_auto_match_ready2 m_x2bs_auto_match_ready2 {get; set;}
		[ProtoMember(11, IsRequired = false)]
		public s_x2bs_match_ready m_x2bs_match_ready {get; set;}
		[ProtoMember(12, IsRequired = false)]
		public s_req_pitcher_throw m_req_pitcher_throw {get; set;}
		[ProtoMember(13, IsRequired = false)]
		public s_req_better_hit m_req_better_hit {get; set;}
		[ProtoMember(14, IsRequired = false)]
		public s_req_result_better_hit m_req_result_better_hit {get; set;}
		[ProtoMember(15, IsRequired = false)]
		public s_x2bs_batter_ready m_x2bs_batter_ready {get; set;}
		[ProtoMember(16, IsRequired = false)]
		public s_req_rematch m_req_rematch {get; set;}
		[ProtoMember(17, IsRequired = false)]
		public s_req_answer_restart_game m_req_answer_restart_game {get; set;}
	}
//end of message Client_BaseballServer


	
	public class PT_BaseballServer_proto_contract
	{
	    public static ArrayList GetTypes()
	    {
	        ArrayList list = new ArrayList();
	        list.Add(typeof(BaseballServer_UserGateServer));
	        list.Add(typeof(s_bs2ug_set_cvar));
	        list.Add(typeof(s_bs2ug_game_end));
	        list.Add(typeof(s_bs2ug_echo));
	        list.Add(typeof(s_bs2ug_error));
	        list.Add(typeof(s_bs2ug_add_discon_tot));
	
	        list.Add(typeof(BaseballServer_Client));
	        list.Add(typeof(s_ans_join_room));
	        list.Add(typeof(s_ans_room_state));
	        list.Add(typeof(s_bs2x_echo));
	        list.Add(typeof(s_ans_chat));
	        list.Add(typeof(s_ans_timer_start));
	        list.Add(typeof(s_bs2x_echo2));
	        list.Add(typeof(s_ans_bs_error));
	        list.Add(typeof(s_bs2x_auto_match_ready2));
	        list.Add(typeof(s_ans_game_start));
	        list.Add(typeof(s_ans_game_round_start));
	        list.Add(typeof(s_bs2x_match_ready));
	        list.Add(typeof(s_ans_pitcher_throw));
	        list.Add(typeof(s_ans_better_hit));
	        list.Add(typeof(s_ans_result_better_hit));
	        list.Add(typeof(s_bs2x_batter_ready));
	        list.Add(typeof(s_ans_change_attack_team));
	        list.Add(typeof(s_ans_game_end));
	        list.Add(typeof(s_bs2x_game_end_other_user_info));
	        list.Add(typeof(s_ans_user_disconnect));
	        list.Add(typeof(s_ans_rematch));
	        list.Add(typeof(s_ans_answer_restart_game));
	
	        list.Add(typeof(UserGateServer_BaseballServer));
	        list.Add(typeof(s_ug2bs_ans_set_cvar));
	        list.Add(typeof(s_ug2bs_game_end));
	        list.Add(typeof(s_ug2bs_echo));
	        list.Add(typeof(s_ug2bs_error));
	        list.Add(typeof(s_ug2bs_add_discon_tot));
	
	        list.Add(typeof(Client_BaseballServer));
	        list.Add(typeof(s_req_room_state));
	        list.Add(typeof(s_x2bs_echo));
	        list.Add(typeof(s_req_chat));
	        list.Add(typeof(s_req_timer_start));
	        list.Add(typeof(s_req_do_disconnect));
	        list.Add(typeof(s_x2bs_echo2));
	        list.Add(typeof(s_req_get_cvar));
	        list.Add(typeof(s_req_set_cvar));
	        list.Add(typeof(s_x2bs_auto_match_ready2));
	        list.Add(typeof(s_x2bs_match_ready));
	        list.Add(typeof(s_req_pitcher_throw));
	        list.Add(typeof(s_req_better_hit));
	        list.Add(typeof(s_req_result_better_hit));
	        list.Add(typeof(s_x2bs_batter_ready));
	        list.Add(typeof(s_req_rematch));
	        list.Add(typeof(s_req_answer_restart_game));
	
	        return list;
	    }
	}
	
}//namespace nPROTO